default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: infinity
  host: localhost

development:
  <<: *default
  database: isha_ops_development

test:
  <<: *default
  database: isha_ops_test

production:
  <<: *default
  database: isha_ops_production
  username: appname
  password: <%= ENV['ISHA_OPS_DATABASE_PASSWORD'] %>
